### ISSUE TITLE
Agregar algoritmos de ordenamiento de listas

### ISSUE THREAD

**Issue by PacoPacoGalindo** [Francisco-Galindo/legendary-octo-happiness#1]
**Is your feature request related to a problem? Please describe.**
No, pero sería muy buena idea, para fines didácticos, agregar nuevo código al proyecto.

**Describe the solution you'd like**
Agregar el algoritmo de bubble-sort al código ya existente

**Additional context**
Seguir trabajando en python.

**Comment by Francisco-Galindo** [comment]
A mí no me gusta tanto el algoritmo de bubble-sort. Me gusta más el de insertion-sort.

¿Te gusta si lo hacemos así?

**Comment by PacoPacoGalindo** [comment]
Sí, me parece utilizar insertion-sort. :)
